//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderPrettifier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolderPrettifier.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;extensions&quot;: {
        ///    &quot;mp4&quot;: 0,
        ///    &quot;mkv&quot;: 0,
        ///    &quot;m4a&quot;: 0,
        ///    &quot;m4v&quot;: 0,
        ///    &quot;f4v&quot;: 0,
        ///    &quot;f4a&quot;: 0,
        ///    &quot;m4b&quot;: 0,
        ///    &quot;m4r&quot;: 0,
        ///    &quot;f4b&quot;: 0,
        ///    &quot;mov&quot;: 0,
        ///    &quot;3gp&quot;: 0,
        ///    &quot;3gp2&quot;: 0,
        ///    &quot;3g2&quot;: 0,
        ///    &quot;3gpp&quot;: 0,
        ///    &quot;3gpp2&quot;: 0,
        ///    &quot;ogv&quot;: 0,
        ///    &quot;ogx&quot;: 0,
        ///    &quot;wmv&quot;: 0,
        ///    &quot;asf&quot;: 0,
        ///    &quot;webm&quot;: 0,
        ///    &quot;flv&quot;: 0,
        ///    &quot;avi&quot;: 0,
        ///    &quot;OP1a&quot;: 0,
        ///    &quot;OP-Atom&quot;: 0,
        ///    &quot;ts&quot;: 0,
        ///    &quot;lxf&quot;: 0,
        ///    &quot;gxf&quot;: 0,
        ///    &quot;vob&quot;: 0,
        ///    &quot;mp3&quot;: 1,
        ///    &quot;aa&quot;: 1,
        ///    &quot;aac&quot;: 1,
        ///    &quot;aax&quot;: 1,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicCatalog {
            get {
                return ResourceManager.GetString("BasicCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder_prettifier_catalog.json.
        /// </summary>
        internal static string CacheFileName {
            get {
                return ResourceManager.GetString("CacheFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/yogesh-aggarwal/folder-prettifier/master/catalog.json.
        /// </summary>
        internal static string CatalogUrl {
            get {
                return ResourceManager.GetString("CatalogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://github.com.
        /// </summary>
        internal static string InternetCheckUrl {
            get {
                return ResourceManager.GetString("InternetCheckUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
