name: Tests

on:
  push:
  pull_request:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run unit tests
        run: dotnet test tests/FolderPrettifier.Tests/FolderPrettifier.Tests.csproj -c Debug